function printfile()
%AvgNDCGListNetGain=importdata('E:\Papers\Programs\LearningtoRankChallenge\ListNetNDCG10.txt','\n');
%AvgNDCGSLAMGain=importdata('E:\Papers\Programs\LearningtoRankChallenge\SLAMNDCG10.txt','\n');
%AvgNDCGSVMGain=importdata('E:\Papers\Programs\LearningtoRankChallenge\SVMNDCG10.txt','\n');
%AvgNDCGPartialGain1=importdata('E:\Papers\Programs\LearningtoRankChallenge\Partial1NDCG10.txt','\n');
%AvgNDCGPartialGain2=importdata('E:\Papers\Programs\LearningtoRankChallenge\Partial2NDCG10.txt','\n');
%AvgNDCGPartialGain3=importdata('E:\Papers\Programs\LearningtoRankChallenge\Partial3NDCG10.txt','\n');
%AvgNDCGPartialGain4=importdata('E:\Papers\Programs\LearningtoRankChallenge\Partial4NDCG10.txt','\n');
%AvgNDCGRandomGain=importdata('E:\Papers\Programs\LearningtoRankChallenge\RandomNDCG10.txt','\n');
%AvgNDCGSLAMGain20=importdata('E:\Papers\Programs\LearningtoRankChallenge\SLAM20NDCG10.txt','\n');
%AvgNDCGSLAMGain=importdata('E:\Papers\Programs\LearningtoRankChallenge\SLAMGAUSSIANNDCG10.txt','\n');

%AvgNDCGListNetGain=importdata('E:\Papers\Programs\MSLTR10K\Experiments\ListNetNDCG10.txt','\n');
%AvgNDCGSLAMGain=importdata('E:\Papers\Programs\MSLTR10K\Experiments\SLAMNDCG10.txt','\n');
%AvgNDCGSVMGain=importdata('E:\Papers\Programs\MSLTR10K\Experiments\SVMNDCG10.txt','\n');

AvgNDCGListNetGain=importdata('E:\Papers\Programs\Yandex\ListNetNDCG10.txt','\n');
AvgNDCGSLAMGain=importdata('E:\Papers\Programs\Yandex\SLAMNDCG10.txt','\n');
%AvgNDCGSVMGain=importdata('E:\Papers\Programs\Yandex\SVMNDCG10.txt','\n');
%AvgNDCGPartialGain=importdata('E:\Papers\Programs\Yandex\PartialNDCG10.txt','\n');
%AvgNDCGRandomGain=importdata('E:\Papers\Programs\Yandex\RandomNDCG10.txt','\n');
AvgNDCGSLAMGain=AvgNDCGSLAMGain(AvgNDCGSLAMGain(:)>0);
disp(AvgNDCGSLAMGain(end-10:end));
%AvgNDCGSVMGain=AvgNDCGSVMGain(AvgNDCGSVMGain(:)>0);
%disp(AvgNDCGSVMGain(end-10:end));
AvgNDCGListNetGain=AvgNDCGListNetGain(AvgNDCGListNetGain(:)>0);
disp(AvgNDCGListNetGain(end-10:end));
%AvgNDCGPartialGain1=AvgNDCGPartialGain1(AvgNDCGPartialGain1(:)>0);
%disp(AvgNDCGPartialGain1(end-10:end));
%AvgNDCGPartialGain2=AvgNDCGPartialGain2(AvgNDCGPartialGain2(:)>0);
%disp(AvgNDCGPartialGain2(end-10:end));
%AvgNDCGPartialGain3=AvgNDCGPartialGain3(AvgNDCGPartialGain3(:)>0);
%disp(AvgNDCGPartialGain3(end-10:end));
%AvgNDCGPartialGain4=AvgNDCGPartialGain4(AvgNDCGPartialGain4(:)>0);
%AvgNDCGPartialGain4=AvgNDCGPartialGain4+0.01;
%disp(AvgNDCGPartialGain4(end-10:end));
%AvgNDCGRandomGain=AvgNDCGRandomGain(AvgNDCGRandomGain(:)>0);
%disp(AvgNDCGRandomGain(end-10:end));
% AvgNDCGSLAMGain20=AvgNDCGSLAMGain20(AvgNDCGSLAMGain20(:)>0);
% disp(AvgNDCGSLAMGain20(end-10:end));
% % AvgNDCGSLAMGain=AvgNDCGSLAMGain(AvgNDCGSLAMGain(:)>0);
% % disp(AvgNDCGSLAMGain(end-10:end));

% 
% % diff=AvgNDCGListNetGain-AvgNDCGSLAMGain5;
% % percentchange5= diff./AvgNDCGSLAMGain5 *100;
% % diff=AvgNDCGListNetGain-AvgNDCGSLAMGain20;
% % percentchange20= diff./AvgNDCGSLAMGain20 *100;
% % diff=AvgNDCGListNetGain-AvgNDCGSLAMGain;
% % percentchange= diff./AvgNDCGSLAMGain *100;
count=size(AvgNDCGSLAMGain,1);
% % %disp(count);
xplot=2:500:40000;
% % % % percentchange=percentchange(xplot);
% % % % disp(percentchange);
% % % % percentchange20=percentchange20(xplot);
% % % % disp(percentchange20);
yplot=AvgNDCGListNetGain(xplot);
yplot1=AvgNDCGSLAMGain(xplot);
%yplot1=AvgNDCGPartialGain4(xplot);
%yplot=AvgNDCGSVMGain(xplot);
%yplot2=AvgNDCGRandomGain(xplot);
% % yplot2=AvgNDCGSLAMGain20(xplot);
% % %yplot1=AvgSLAMLoss(xplot);
% %hand=plot(xplot,yplot,'r', xplot, yplot1, 'b', xplot, yplot2, 'g');
%hand=plot(xplot,yplot,'-*', xplot,yplot1,'-+', xplot, yplot2, '--');
 hand=plot(xplot,yplot1,'-*', xplot,yplot,'-+');
set(hand,'LineWidth',2);
set(gca, 'YLim',[0.6 1.0],'fontsize',20);
xlabel('Iterations');
ylabel('AverageNDCG');
% %hleg = legend('ListNet:NDCG@10', 'PerceptronNewHinge:NDCG@10', 'PerceptronOriginHinge:NDCG@10');
hleg = legend('SLAM:NDCG@10', 'ListNet:NDCG@10');
rect = [0.70, 0.11, .15, .23];
set(hleg, 'position', rect, 'FontSize',20);
% % % hand= plot(xplot,percentchange,'r');
% % % set(hand,'LineWidth',2);
% % % set(gca, 'fontsize',20);
% % % xlabel('Iterations');
% % % ylabel('PercentGain');
end